[profile.default]
src = "src"
out = "out"
libs = ["lib"]
sender = "0xf2cacc05ab5a161cb9bb31ee2d3a9b9fb05481a4"
force = false
optimizer = true
auto_detect_remappings = false
optimizer_runs = 999999
evm_version = "berlin"
bytecode_hash = "ipfs"
extra_output_files = ["metadata"]

[rpc_endpoints]
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"
pangolin = "https://pangolin-rpc.darwinia.network"
crab = "https://crab-rpc.darwinia.network"
dev = "http://192.168.132.159:9944"

[fmt]
line_length=120
multiline_func_header='all'
bracket_spacing=true
wrap_comments=true
ignore = ['script/Deploy.s.sol', 'test/BeaconLightCLient.t.sol']
